<?php
// Generated by installer on 2025-10-31 00:42:32
// NOTE: Keep this file out of version control. It contains secrets.

define('DB_HOST', 'localhost');
define('DB_NAME', 'blluepan_up');
define('DB_USER', 'blluepan_up');
define('DB_PASS', 'Ha42684268@');
define('DB_CHARSET', 'utf8mb4');

define('BOT_TOKEN', '8339562059:AAFqDEttPELabCg5IMO_8oC3EIOrnJL1cyM');
define('ADMIN_ID', '7581381606');
define('ADMIN_KEY', 'Ha42684268@');
define('CHANNEL_USERNAME', '@Dlzhinkurdi');
define('WEBHOOK_SECRET', 'd53a7a1d0c1da140e35e40d24e56b551');

define('SITE_URL', 'https://blluepanel.ir');
define('WEBHOOK_URL', SITE_URL . '/webhook.php');

define('SESSION_LIFETIME', 86400 * 30);
define('CSRF_TOKEN_LENGTH', 32);
define('TIMEZONE', 'Asia/Tehran');

// Build application version from VERSION + BUILD if available
if (!function_exists('app_version')) {
    function app_version() {
        $base = @file_get_contents(__DIR__ . '/VERSION');
        $base = $base ? trim($base) : '2.1.0';
        $build = @file_get_contents(__DIR__ . '/BUILD');
        $build = $build ? (int)trim($build) : 0;
        return $build > 0 ? ($base . '+build.' . $build) : $base;
    }
}
define('APP_VERSION', app_version());

define('ENVIRONMENT', 'production');
// DEBUG_MODE is disabled by default in production. Enable temporarily only when
// actively debugging and revert as soon as possible to avoid exposing secrets.
define('DEBUG_MODE', false);

// Do not display PHP errors in production. Keep error reporting for logs but
// hide display to users. If you need to debug, set DEBUG_MODE = true manually.
@ini_set('display_errors', DEBUG_MODE ? '1' : '0');
@ini_set('display_startup_errors', DEBUG_MODE ? '1' : '0');
@error_reporting(E_ALL);
define('CACHE_ENABLED', true);
define('CACHE_TTL', 300);
define('MAINTENANCE_MODE', false);

date_default_timezone_set(TIMEZONE);
